### ISSUE TITLE
测试了一下，先提一几小问题

### ISSUE THREAD

**Issue by youanan** [xiaoshun007/12306Python#1]
非常感谢你的创作，试用了一下，发现有几个小问题：

1. 车次没有全选，没有K字头的火车，春运有个K字头也比较幸福啦
2，查询过程中，12306只要出现对话框，程序就中止了。

希望慢慢完善吧

**Comment by xiaoshun007** [comment]
@youanan K开头车次已经支持了，需要K开头车次的，在config.ini的train_types添加“K”即可
