### ISSUE TITLE
MAC 浏览器地址如何更改

### ISSUE THREAD

**Issue by kaizhang0124** [xiaoshun007/12306Python#11]
您好  请问 Mac 浏览器地址如何更改executable_path= ???

**Comment by iyongjie** [comment]
Mac上默认为/usr/local/bin/chromedriver

**Comment by kaizhang0124** [comment]
from splinter.browser import Browser
ImportError: No module named splinter.browser  这个是错误是要导入splinter.browser吗

**Comment by iyongjie** [comment]
先安装下splinter模块

**Comment by xiaoshun007** [comment]
@kaizhang0124 iyongjie同学已经给出了答案，
1、executable_path这个地址根据你本地下载的chromedriver来指定就可以了
2、No module named splinter.browser 在控制台执行命令：pip install splinter就可以了
