### ISSUE TITLE
关于车站名不在列表中的问题

### ISSUE THREAD

**Issue by ch8936** [xiaoshun007/12306Python#14]
例如买从福田到湘潭北，这两个车站都不在列表中，这时候就需要在12306官网中填上出发地，目的地之后，点击查询，打开F12调试窗口，Network--all--haders--Query String Parameters。显示leftTicketDTO.from_station:NZQ.那么这个NZQ就是出发地福田的代号，leftTicketDTO.to_station:EDQ，同理EDQ就是湘潭北的代号。

**Comment by xiaoshun007** [comment]
@ch8936 在city_code.txt文件中已经添加了这两个站的信息了，如果还有问题可以自行修改下city_code.txt就可以了，问题就先关闭了哈
