### ISSUE TITLE
调用浏览器出错

### ISSUE THREAD

**Issue by izzlins** [xiaoshun007/12306Python#15]
打开火狐后，只停留在主页面，报错Message: Service D:\Program Files (x86)\Firefox\firefox.exe unexpectedly exited. Status code was: 1，请问这个该怎么办

**Comment by xiaoshun007** [comment]
@izzlins 程序用的chromedriver，更换为chrome，修改config.ini中的executable_path为本机的chromedriver解压路径
如果想用firefox，参照这里（http://splinter.readthedocs.io/en/latest/drivers/firefox.html）可以下载firefox的驱动，并将config.ini中driver_name = chrome，改为driver_name = firefox，executable_path = 【firefox驱动解压路径】

**Comment by xiaoshun007** [comment]
一周了，应该解决了吧，问题先关闭了
