### ISSUE TITLE
windows10无法运行

### ISSUE THREAD

**Issue by marcusbai** [xiaoshun007/12306Python#16]
在Windows10 使用exe文件时提示 此应用无法在你的电脑运行
![snipaste_20180111_201323](https://user-images.githubusercontent.com/16847894/34825143-3ba49700-f70c-11e7-9cf6-c6fbec933b28.png)

**Comment by xiaoshun007** [comment]
额，由于是基于win7转换到可执行程序，兼容性可能没有覆盖到，方便的话可以clone最新源码，用pyinstaller 在本地转换一下

**Comment by marcusbai** [comment]
好的，我试试，刚开始接触python
