### ISSUE TITLE
停在了等待验证码

### ISSUE THREAD

**Issue by cloverapp1** [xiaoshun007/12306Python#17]
===========hack12306 begin===========
映射出发地、目的地...
加载配置文件...
开始登录...
等待验证码，自行输入...

到这就停了，进行不下去，一直这样，请问是配置错了吗

**Comment by xiaoshun007** [comment]
@cloverapp1 正常的，还不支持自动输入验证码，需要手动输入验证码，点击登录

**Comment by Jasonjiang27** [comment]
我也停在这里，输入验证码后没反应，，终端有个报错：ERROR:shader_disk_cache.cc(257)] Failed to create shader cache entry: -2
请问这是什么原因？
