### ISSUE TITLE
有个bug，在config.ini设置了seat_type=软卧, 居然给提交了“无座”。

### ISSUE THREAD

**Issue by tonyxyl** [xiaoshun007/12306Python#19]
如题，seat_type可否改成支持多种座次类型，像train_types那样

**Comment by xiaoshun007** [comment]
@tonyxyl 这个seat_type是用来在确认选座时那个选择座位类型下拉框，所以只支持单个，因为提交订单一个人是只能选择一种座次的；train_types是用来查询的，所以支持多个。你说的这种场景应该是想要查询的时候能根据座次来过滤，目前还不支持

**Comment by ihrthk** [comment]
查询的时候能根据座次来过滤,比如值定硬卧，那个车次都行，这个很重要，考一下实现以下嘛。
