### ISSUE TITLE
无法提交订单

### ISSUE THREAD

**Issue by Severxsh** [xiaoshun007/12306Python#2]
测试了一下，'ElementList' object has no attribute 'click'，无法提交订单

**Comment by xiaoshun007** [comment]
@Severxsh 在哪一步的时候报的错

**Comment by Severxsh** [comment]
[812:800:0107/094850.614:ERROR:service_manager.cc(157)] Connection InterfaceProviderSpec prevented service: content_renderer from binding interface: blink::mojom::ReportingServiceProxy exposed by: content_browser     Chrome是63的，ChromeDriver也是2.34

**Comment by xiaoshun007** [comment]
@Severxsh 网上说可能是v63 chrome的bug，试着降一个chrome版本试试
“It actually isnt an issue with chromedriver but rather with chrome v63. Chrome v63 has bugs in its ShaderCache which is causing this. The easiest fix is downgrading to chrome v60-61 and using chromedriver v2.33 Worked for me”

**Comment by Choaya-Elvis** [comment]
我把 order：车次 这个参数设置为默认 0,可以正常进行预订
但是我包 order 设置成为 1就出现了 'ElementList' object has no attribute 'click'这个问题
我觉得应该不是v63 chrome的bug导致的这个问题吧

**Comment by xiaoshun007** [comment]
@Choaya-Elvis order那个地方暂时还有点问题，还只能支持0
