### ISSUE TITLE
这个只能用chrome浏览器嘛？火狐怎么配置那个驱动路径？我在火狐的安装目录下只看到firefox.exe

### ISSUE THREAD

**Issue by Lz-Stone** [xiaoshun007/12306Python#20]

**Comment by xiaoshun007** [comment]
如果想用firefox，参照这里（http://splinter.readthedocs.io/en/latest/drivers/firefox.html）可以下载firefox的驱动，并将config.ini中driver_name = chrome，改为driver_name = firefox，executable_path = 【firefox驱动解压路径】
