### ISSUE TITLE
ModuleNotFoundError: No module named 'splinter'

### ISSUE THREAD

**Issue by yinmazhong** [xiaoshun007/12306Python#4]
感谢分享，下面这个问题是因为少了什么？
google了一下，没有类似的信息

Traceback (most recent call last):
  File "hack12306.py", line 19, in <module>
    from splinter.browser import Browser
ModuleNotFoundError: No module named 'splinter'

**Comment by xiaoshun007** [comment]
本地没有这个包，执行pip install splinter
