### ISSUE TITLE
 os.path.basename(self.path), self.start_error_message)

### ISSUE THREAD

**Issue by asasdasasd** [xiaoshun007/12306Python#7]
os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by xiaoshun007** [comment]
@asasdasasd 检查下executable_path这个配置的chromedriver驱动路径是否正确
